# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLI76nNOZwCorC4Q641a-4m-hpAnKG9h
"""

app = Flask(__name__)

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html>
<head>
    <title>Voting Eligibility Checker</title>
</head>
<body>
    <h2>Enter Your Age</h2>
    <form method="post">
        <input type="number" name="age" required>
        <button type="submit">Check Eligibility</button>
    </form>
    {% if result is not none %}
        <h3>{{ result }}</h3>
    {% endif %}
</body>
</html>
'''

@app.route("/", methods=["GET", "POST"])
def check_eligibility():
    result = None
    if request.method == "POST":
        try:
            age = int(request.form["age"])
            if age >= 18:
                result = "You are eligible to vote."
            else:
                result = "You are not eligible to vote."
        except ValueError:
            result = "Invalid input. Please enter a valid age."
    return render_template_string(HTML_TEMPLATE, result=result)

if __name__ == "__main__":
    app.run(debug=True)